### ISSUE TITLE
Consultar Partes

### ISSUE THREAD

**Issue by OEDOARDO** [adev-victord/mov_processual_pjepb#2]
Boa  noite amigo!

Excelentíssimo código, estou tentando adaptar para tambémm consultar  as  partes do processo, no meu caso, a parte passiva. Tem alguma dica? Grande abraço!

**Comment by odantasvictor** [comment]
Olá @OEDOARDO.

Eu, particularmente, sou fã da estrutura:
```
while True:
    try:
        trecho p/ coleta da parte
        break
    except:
        continue
```

Isso fará o teu bot tentar coletar um dado até conseguir, vencendo a instabilidade do PJE. No trecho da coleta, basta passar o trecho do selenium (ex.: self.web_driver.find_element(By.ID, 'id_do_elemento_parte_passiva').text), manuseando como preferir.

Caso não tenha certeza que o dado estará lá, remove o while True, assim ele só tenta capturar e, caso não consiga, segue o fluxo da automação.

**Comment by OEDOARDO** [comment]
Vamos lá,

Eu inclui a coluna "CPF" dentro do arquivo consultas_classmetod.py na linha 77, ficando:

 self.df_resultado = pd.DataFrame({'Processo': [], 'UF': [], 'Movimentação': [], 'Data da Movimentação': [], 'Feedback': [], 'URL Consulta': [], 'CPF': []})

Dessa forma, ao criar o arquivo de resultado, o CPF é incluído. Minha dificuldade está sendo dentro do arquivo bots_pje.py:

Tentei deixar da seguinte forma, mais não consegui pegar o dado do CPF:

def coletar_cpf  (self):
        try:
            cpf  = self.web_driver.find_elements(By.CSS_SELECTOR, 'span[id*=":processoPartesPoloPassivoResumidoList:"]').text 
        except:
            continue

    def coletar_movimentacoes(self, pandas, processo):
        try:
            movimentacoes = self.web_driver.find_elements(By.CSS_SELECTOR, 'span[id*=":processoEvento:"]')
            
            for index, movimentacao in enumerate(movimentacoes):
                movimentacao_div = movimentacao.text.split(' - ')
                if index == 0:
                    lista_dados = [processo, self.dados_uf['uf'], movimentacao_div[1], movimentacao_div[0], 'Consulta Realizada', 'URL',cpf]
                else:
                    lista_dados = [processo, self.dados_uf['uf'], movimentacao_div[1], movimentacao_div[0], '', '', cpf]
                pandas.anotar_consulta(lista_dados)
        except Exception as e:
            return e

**Comment by OEDOARDO** [comment]
Poderia me dar uma ajuda nessa parte?

**Comment by odantasvictor** [comment]
Conforme repassado...

Adicionar a função abaixo, chamando ela antes da função coletar_movimentacoes().
Também é necessário: 1) adicionar a coluna na estrutura do pandas; 2) adicionar o self.cpf_cnpj_reu no lista_dados, na ordem da coluna desejada;

Função para coleta do cpf_cnpj do réu:
```
def coletar_cpf_cnpj(self):
    try:
        self.cpf_cnpj_reu = ''
        self.cpf_cnpj_reu = self.web_driver.find_element(By.CSS_SELECTOR, 'tbody[id*="processoPartesPoloPassivoResumidoList:tb"]').find_element(By.CSS_SELECTOR, 'span.text-bold').text.split(': ')[-1].split(' (')[0]
    except Exception as e:
        print('Erro na coleta do CPF/CNPJ:', e)
```

**Comment by OEDOARDO** [comment]
Perfeito, funcionou 100%, muito obrigado pelo auxílio e ensino, agregou bastante.

**Comment by OEDOARDO** [comment]
@odantasvictor para a nova estrutura da ferramenta essa função ainda vai funcionar?

**Comment by odantasvictor** [comment]
Não, precisa adaptar o trecho de anotação do Pandas e substiuir por anotações no banco. Depende da criação das tabelas e etc.
